worker_processes auto;
pid              run/nginx.pid;
error_log        run/error.log warn;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile      on;
    server_tokens off;

    access_log run/access.log;

    client_body_temp_path run/tmp/client_body;
    proxy_temp_path       run/tmp/proxy;
    fastcgi_temp_path     run/tmp/fastcgi;
    uwsgi_temp_path       run/tmp/uwsgi;
    scgi_temp_path        run/tmp/scgi;

    # Балансировка
    upstream todo_backend {
        zone todo_backend 1m;
        server 127.0.0.1:5040 max_fails=1 fail_timeout=10s;
        server 127.0.0.1:5041 max_fails=1 fail_timeout=10s;
        keepalive 16;
    }

    # Rate limit
    limit_req_zone   $binary_remote_addr zone=api:10m rate=5r/s;
    limit_req_status 429;
    limit_req_log_level warn;

    include sites/*.conf;
}
