# Основной проект
#   /api/ - балансировка
#   /docs/ - alias
#   /admin - basic auth
server {
    listen 443 ssl;
    http2  on;
    server_name todo.local;

    include snippets/ssl.conf;
    include snippets/errors.conf;

    # Сборка фронта
    root  ../lab0/frontend/dist;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /api/ {
        limit_req zone=api burst=10 nodelay;

        include    snippets/proxy.conf;
        proxy_pass http://todo_backend;
    }

    # alias
    location /docs/ {
        alias www/docs/;
    }

    # Закрыто авторизацией
    location /admin {
        auth_basic           "Admin area";
        auth_basic_user_file .htpasswd;

        root www;    # /admin/index.html → lab1/www/admin/index.html
    }
}
