FROM golang:1.25.11 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o server ./internal


FROM alpine:3.22.1

RUN adduser -D backend_user

WORKDIR /app

COPY --from=builder /app/server ./server
COPY --from=builder /app/migrations ./migrations

USER backend_user

EXPOSE 5040

HEALTHCHECK --interval=60s --timeout=5s --start-period=10s --start-interval=2s --retries=3 CMD wget --spider -q http://localhost:5040/health || exit 1

CMD ["./server"]
